In [7]:
import numpy as np

In [8]:
import pandas as pd

In [94]:
from sklearn.model_selection import train_test_split

In [9]:
array1 = np.array([1,2,3])

In [10]:
array1

array([1, 2, 3])

In [15]:
type(array1)

numpy.ndarray

In [17]:
array1.shape

(3,)

In [18]:
array1.ndim

1

In [19]:
array2 = np.array([[1,2,3], [2,3,4]])

In [20]:
array2

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
type(array2)

numpy.ndarray

In [23]:
array2.shape

(2, 3)

In [24]:
array2.ndim

2

In [25]:
array3 = np.array([[[1,2,3],[2,3,4]],
                   [[5,6,7],[6,7,8]]])

In [26]:
array3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 6, 7],
        [6, 7, 8]]])

In [28]:
array3.shape

(2, 2, 3)

In [29]:
array3.ndim

3

In [38]:
list1 = ['1','2',3]
type(list1)

list

In [39]:
array1 = np.array(list1)
type(array1)

numpy.ndarray

In [40]:
array1.dtype

dtype('<U11')

In [41]:
array_int = np.array([1,2,3])
array_int.dtype

dtype('int32')

In [42]:
array_float = array_int.astype('float64')

In [43]:
array_float.dtype

dtype('float64')

In [45]:
array_float1 = np.array([1.1,2.2,3.8])
array_int2 = array_float1.astype('int32')
array_int2

array([1, 2, 3])

In [49]:
np.arange(10).dtype

dtype('int32')

In [50]:
np.arange(1,11,dtype='float64')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
np.zeros((3,2),dtype='int32')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [54]:
np.ones((3,2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [57]:
array1 = np.arange(10)

In [58]:
array1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [59]:
array1.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
org_array = np.array([3,1,9,5])
org_array

array([3, 1, 9, 5])

In [68]:
np.sort(org_array)

array([1, 3, 5, 9])

In [69]:
org_array

array([3, 1, 9, 5])

In [70]:
np.ndarray.sort(org_array) 

In [71]:
org_array

array([1, 3, 5, 9])

In [73]:
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [76]:
array2d = np.array([[8,12],
                   [7,1]])
array2d

array([[ 8, 12],
       [ 7,  1]])

In [77]:
np.sort(array2d)

array([[ 8, 12],
       [ 1,  7]])

In [78]:
np.sort(array2d, axis=0)

array([[ 7,  1],
       [ 8, 12]])

In [79]:
np.sort(array2d, axis=1)

array([[ 8, 12],
       [ 1,  7]])

In [80]:
org_array = np.array([3,1,9,5])
org_array

array([3, 1, 9, 5])

In [81]:
np.argsort(org_array)

array([1, 0, 3, 2], dtype=int64)

In [82]:
np.argmax(org_array)

2

In [86]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8],
              [9,10],
              [11,12],
              [13,14]])

In [87]:
np.dot(a,b)
# (2,3) (4,2) 는 오류

ValueError: shapes (2,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)

In [88]:
np.dot(b,a)
# (4,2) (2,3)은 가능 -> (4,3)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105],
       [ 69,  96, 123]])

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
np.dot(a.T,b.T)

array([[ 39,  49,  59,  69],
       [ 54,  68,  82,  96],
       [ 69,  87, 105, 123]])

In [96]:
import sklearn
print(sklearn.__version__)

0.24.2


# 붓꽃 품종 예측

In [97]:
from sklearn.datasets import load_iris

In [98]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [101]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [106]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [105]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [107]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [108]:
import pandas as pd

In [110]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [112]:
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

### 학습용과 테스트용으로 나눈다

In [116]:
X_train, X_test, y_tarin, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=11)

In [120]:
from sklearn.tree import DecisionTreeClassifier

In [121]:
dt_clf = DecisionTreeClassifier(random_state=11)

### 학습

In [123]:
dt_clf.fit(X_train, y_tarin)

DecisionTreeClassifier(random_state=11)

### 예측

In [126]:
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [127]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

### 예측 정확도

In [132]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9333333333333333

In [135]:
dt_clf.predict( [[5.6, 3.2, 4.7, 1.4]] )

array([1])

In [139]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [141]:
type(iris.feature_names)

list

In [147]:
type(iris.feature_names)

list

In [148]:
len(iris.feature_names)

4

In [153]:
type(iris.target_names)

numpy.ndarray

In [154]:
len(iris.target_names)

3

In [155]:
type(iris.data)

numpy.ndarray

In [156]:
iris.data.shape

(150, 4)

In [157]:
type(iris.target)

numpy.ndarray

In [158]:
iris.target.shape

(150,)

In [161]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3