In [3]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
import pickle

In [4]:
df = pd.read_csv('배추가격_data.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2922 entries, 0 to 2921
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   year      2922 non-null   int64  
 1   avgTemp   2922 non-null   float64
 2   minTemp   2922 non-null   float64
 3   maxTemp   2922 non-null   float64
 4   rainFall  2922 non-null   float64
 5   avgPrice  2922 non-null   int64  
dtypes: float64(4), int64(2)
memory usage: 137.1 KB


In [14]:
df.tail()

year  avgTemp  minTemp  maxTemp  rainFall  avgPrice
2917  20171227     -3.9     -8.0      0.7       0.0      2865
2918  20171228     -1.5     -6.9      3.7       0.0      2884
2919  20171229      2.9     -2.1      8.0       0.0      2901
2920  20171230      2.9     -1.6      7.1       0.6      2901
2921  20171231      2.1     -2.0      5.8       0.4      2901

In [7]:
X = df.iloc[:,1:5]

In [8]:
X.head(2)

avgTemp  minTemp  maxTemp  rainFall
0     -4.9    -11.0      0.9       0.0
1     -3.1     -5.5      5.5       0.8

In [9]:
y = df['avgPrice']

In [10]:
y.head(2)

0    2123
1    2123
Name: avgPrice, dtype: int64

In [11]:
X = X.values.reshape(-1,4)

In [12]:
X

array([[ -4.9, -11. ,   0.9,   0. ],
       [ -3.1,  -5.5,   5.5,   0.8],
       [ -2.9,  -6.9,   1.4,   0. ],
       ...,
       [  2.9,  -2.1,   8. ,   0. ],
       [  2.9,  -1.6,   7.1,   0.6],
       [  2.1,  -2. ,   5.8,   0.4]])

In [11]:
X.shape

(2922, 4)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1)

In [17]:
X_train.shape

(2629, 4)

In [18]:
X_train

array([[15.5, 13.3, 19.2,  0.3],
       [ 2.8, -0.3,  6.4,  0.1],
       [10.5,  4.3, 18.4,  0. ],
       ...,
       [21.7, 17.2, 27.2,  0.4],
       [ 0.9, -3.2,  4.6,  0.3],
       [12.1,  9.2, 17.3,  0.3]])

In [21]:
X_train.dtype

dtype('float64')

In [14]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
prediction = lr.predict(X_test)

In [16]:
df.sample(1)

year  avgTemp  minTemp  maxTemp  rainFall  avgPrice
2391  20160719     25.0     20.4     30.0       0.1      3351

In [17]:
data = [[21.3,19.2,26,4]]

In [18]:
lr.predict(data)

array([3495.78636931])

In [19]:
import pickle

In [20]:
with open('pricemodel','wb') as f:
    pickle.dump(lr,f)